export const categoryTopics: Record<string, string[]> = {
    "general-knowledge": [
        "Languages MCQs",
        "Public Administration MCQs",
        "List of International Boundary Lines",
        "World’s Famous Airlines – One-Liner",
        "Environmental Science MCQs",
        "National Sports of Countries",
        "Civil Servants Acts 1973",
        "Greenwich Maritime and Time Zone MCQs",
        "Famous Lakes MCQs List",
        "World Intelligence Agencies MCQs",
        "European Union EU MCQs",
        "Planets MCQs with Answers",
        "Olympic Games MCQs",
        "Cricket MCQs with Answers",
        "Vitamins MCQs with Answers",
        "Sociology MCQs",
        "Pakistan General Knowledge MCQs",
        "Landlocked Countries in World",
        "7 Continents MCQs",
        "News Agency MCQs with Answers"
    ],
    "current-affairs": [
        "Pakistan Current Affairs MCQs November 2024",
        "Pakistan Current Affairs MCQs October 2024",
        "Pakistan Current Affairs September 2024",
        "Pakistan Current Affairs August 2024",
        "Pakistan Current Affairs July 2024",
        "Pakistan Current Affairs MCQs June 2024",
        "Pakistan Current Affairs MCQs May 2024",
        "Pakistan Current Affairs MCQs April 2024",
        "World Current Affairs November 2024",
        "International Current Affairs MCQs October 2024",
        "World Current Affairs September 2024",
        "International Current Affairs MCQs August 2024",
        "International Current Affairs July 2024",
        "World Current Affairs MCQs June 2024",
        "World Current Affairs MCQs May 2024",
        "World Current Affairs MCQs April 2024",
        "World Current Affairs MCQs March 2022"
    ]
};
